project_id = "wxkfpvapboxerzlsqopq"

[functions.murf-tts]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.scan-crop]
verify_jwt = false

[functions.fetch-market-prices]
verify_jwt = false
